baseURL = "https://pertsfoundry.com/"
title = "Perts Foundry"
languageCode = "en-us"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableGitInfo = true

[build]
  writeStats = true

[permalinks]
  [permalinks.page]
    blog = "/blog/:slug/"
    services = "/services/:slug/"
    case-studies = "/case-studies/:slug/"
    small-business = "/small-business/:slug/"
  [permalinks.section]
    blog = "/blog/"
    services = "/services/"
    case-studies = "/case-studies/"
    small-business = "/small-business/"

[sitemap]
  changefreq = ""
  priority = -1

[outputs]
  home = ["HTML", "RSS", "JSON"]
