languageCode = "en"
languageName = "English"
weight = 1
title = "Perts Foundry"

[params]
  displayName = "EN"
  isoCode = "en"

[params.author]
  name = "Seth Perts"
  image = "img/author.jpg"
  headline = "DevOps consulting that helps scaling teams ship faster and spend less on infrastructure."
  email = "contact@pertsfoundry.com"
  links = []
