colorScheme = "perts-forge-blue"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
logo = "img/logo/perts-foundry-horizontal-light.svg"
secondaryLogo = "img/logo/perts-foundry-horizontal-dark.svg"

[homepage]
  layout = "background"
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "/blog"
  cardView = false

[article]
  showDate = false
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showTableOfContents = true
  showRelatedContent = false

[list]
  showBreadcrumbs = true
  groupByYear = false

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
