colorScheme = "perts-forge-blue"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
logo = "img/logo/perts-foundry-horizontal-dark.svg"
secondaryLogo = "img/logo/perts-foundry-horizontal-light.svg"
disableTextInHeader = true
enableStructuredBreadcrumbs = true
turnstileSiteKey = "0x4AAAAAACxUbBWxqsfKfvH-"

[homepage]
  layout = "background"
  homepageImage = "img/background.jpg"
  showRecent = false
  showRecentItems = 3
  showMoreLink = false
  showMoreLinkDest = "/case-studies"
  cardView = false

[article]
  showWordCount = false
  showDate = false
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showTableOfContents = true
  showRelatedContent = false

[list]
  showBreadcrumbs = true
  groupByYear = false

[header]
  layout = "fixed-fill-blur"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
